"""
Django settings for bookshop project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'px0w=uy6ercu5$ru+7l(($t6gyj$^lg5cjcv5gg0eru^$o7s#i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'paypal.standard.ipn',
    'coupons.apps.CouponsConfig',
    'payment.apps.PaymentConfig',
    'order.apps.OrderConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':"bookshop1",
        'USER':"bookshop1user",
        "PASSWORD":"1234567890",
        'PORT':"3306",
        'HOST':"127.0.0.1",
        'OPTIONS':{
            'init_command':"SET sql_mode='STRICT_TRANS_TABLES'",
            'charset':'utf8mb4',
        }
        },
    'pro_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':"bookshop2",
        'USER':"bookshop2user",
        "PASSWORD":"1234567890",
        'PORT':"3306",
        'HOST':"127.0.0.1",
        },
    'ord_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':"bookshop3",
        'USER':"bookshop3user",
        "PASSWORD":"1234567890",
        'PORT':"3306",
        'HOST':"127.0.0.1",
        }
}

#ROUTER_PATH = os.path.join(BASE_DIR,'router/router.DBRouter')
#DATABASES_ROUTERS =[ROUTER_PATH]

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media/')

CART_SESSION_ID = 'cart'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USE_TLS = False
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'xiuzhikong@163.com'
EMAIL_HOST_PASSWORD = '163smtp'
#DEFAULT_FROM_EMAIL = 'kongxiuzhi@163.com'

PAYPAL_RECEIVER_EMAIL = 'xiuzhikong@163.com'
PAYPAL_TEST = True

LANGUAGES = (
    ('en','English'),
    ('zh-CN',u'简体中文')
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR,'locale/')
)

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1