# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=13, validators=[shop.models.BookEditValidator.isdigit, django.core.validators.MaxLengthValidator(13), django.core.validators.MinLengthValidator(13)], verbose_name='ISBN13')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=128, verbose_name='Subtitle')),
                ('pages', models.PositiveSmallIntegerField(blank=0, default=0, null=0, verbose_name='Pages')),
                ('author', models.CharField(blank=True, default='', max_length=256, verbose_name='Author')),
                ('translator', models.CharField(blank=True, default='', max_length=256, verbose_name='Translator')),
                ('publisher', models.CharField(blank=True, default='', max_length=256, verbose_name='Publisher')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Price')),
                ('binding', models.CharField(blank=True, default='', max_length=128, verbose_name='Binding')),
                ('pubdate', models.DateField(blank=True, help_text='(.etc 2017-12-12)', null=True, verbose_name='Date Published')),
                ('authorDesc', models.TextField(blank=True, default='', verbose_name='Author Desc')),
                ('cover', models.ImageField(default='defa/1.jpg', upload_to='face/%Y/%m/%d', verbose_name='Book Cover')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Summary')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Rating')),
                ('count', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Count')),
                ('sale', models.BooleanField(default=True, verbose_name='Sale')),
                ('douban', models.URLField(blank=True, default='', max_length=255, verbose_name='douban')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Category'),
        ),
    ]
