# Generated by Django 2.0 on 2018-01-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count',
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(blank=True, help_text='(.etc 2018-01-03)', null=True, verbose_name='Date Published'),
        ),
    ]
