# Generated by Django 2.0 on 2018-01-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180106_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(blank=True, help_text='(.etc 2018-01-15)', null=True, verbose_name='Date Published'),
        ),
    ]
